Fill in more fields for packaging and ensure templates check for dependencies before activation

diff --git a/src/templates/local-x11/pre-activate b/src/templates/local-x11/pre-activate
--- a/src/templates/local-x11/pre-activate
+++ b/src/templates/local-x11/pre-activate
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+command -v jq || { echo "Could not find jq. More info: https://github.com/stedolan/jq/wiki/Installation"; exit 1; }
+
 SETTINGS_DIR="$PWD/.vscode"
 SETTINGS="$SETTINGS_DIR/settings.json"
 if [ -f "$SETTINGS" ]
